import {Photo} from "./Photo";
import {Document} from "./Document";
import {PropertyType, PropertySubtype, DealStatus, PropertyUse, Tenancy} from "./enums";
import {Model} from "../Model";

export interface Property extends Model {

	id?: number;
	broker_id: number;
	second_broker_id?: number;
	third_broker_id?: number;
	address: string;
	city: string;
	state: string;
	zip: string;
	county: string;
	market?: string;
	submarket?: string;
	cross_streets?: string;
	location_description: string;
	latitude?: number;
	longitude?: number;
	name?: string;
	property_type_id: PropertyType;
	property_subtype_id: PropertySubtype;
	zoning?: string;
	apn?: string;
	lot_size_acres?: number;
	you_tube_url?: string;
	mls_id?: string;
	building_size_sf: number;
	ceiling_height_f?: number;
	renovated?: number;
	parking_ratio?: number;
	number_of_parking_spaces?: number;
	utilities_description?: string;
	additional_property_subtype_ids?: PropertySubtype[];
	traffic_count?: number;
	traffic_count_street?: string;
	traffic_count_frontage?: number;
	site_description?: string;  // surrounding businesses
	number_of_units?: number;
	number_of_floors?: number;
	year_built?: number;
	occupancy_pct?: number;
	building_class: string;
	sale?: boolean;
	sale_deal_status_id?: DealStatus;
	auction?: boolean;
	hide_sale_price?: boolean;
	sale_price_dollars?: number;
	sale_title?: string;
	sale_description?: string;
	sale_expiration?: Date;
	sale_bullets?: string[];
	sale_pdf_url?: string;
	property_use_id?: PropertyUse;
	tenancy_id?: Tenancy;
	cap_rate_pct?: number;
	net_operating_income?: number;
	land_legal_description?: string;
	lease?: boolean;
	lease_title?: string;
	lease_description?: string;
	lease_expiration?: Date;
	lease_bullets?: string[];
	lease_pdf_url?: string;
	photos?: Photo[];
	documents?: Document[];
	proposal?: boolean;
	sale_listing_url?: string;
	sale_listing_published?: string;
	sale_listing_searchable?: string;
	lease_listing_url?: string;
	lease_listing_published?: string;
	lease_listing_searchable?: string;
	external_id?: number;
	custom_fields?: {[key: string]: any};
	created_at?: Date;
	updated_at?: Date;
}